### ISSUE TITLE
Need Info

### ISSUE THREAD

**Issue by gotspatel** [tunis78/roundcube-hms_rules#4]
Can this plugin work with Roundcube 1.4.11 and Elastic Skin? 

Hmailserver and Roundcube is on the same server

I am getting error 

FILE NOT FOUND
The requested resource was not found!
Please contact your server-administrator.

Failed request: localhost/?_task=settings&_action=plugin.rules

**Comment by tunis78** [comment]
Elastic skin is not included

**Comment by gotspatel** [comment]
Thanks for the info. Is there any change you might get Time to add it ;-)
